In [2]:
import pandas as pd

In [2]:
data={
    "Возраст":[25,30,22],
    "Город":["Москва","СПб","Казань"]
}
df = pd.DataFrame(data, index=["Анна","Иван","Ольга"])
print(df)

       Возраст   Город
Анна        25  Москва
Иван        30     СПб
Ольга       22  Казань

In [3]:
print(df["Возраст"])

Анна     25
Иван     30
Ольга    22
Name: Возраст, dtype: int64

Преобразование Series в DataFrame

In [4]:
s = pd.Series([10,20,30], index=['a','b','c'])
df = s.to_frame(name='Значение')
print(df)

   Значение
a        10
b        20
c        30

In [5]:
s = df['Значение']
print(s)

a    10
b    20
c    30
Name: Значение, dtype: int64

In [8]:
data={
    "Имя":["Анна","Иван","Ольга"],
    "Возраст":[25,30,22],
    "Город":["Москва","СПб","Казань"]
}
df = pd.DataFrame(data)
print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [9]:
ages = pd.Series([25,30,22], index=["a","b","c"])
cities = pd.Series(["Москва","СПб","Казань"], index=["a","b","c"])
df= pd.DataFrame({"Возраст": ages, "Город": cities})
print(df)

   Возраст   Город
a       25  Москва
b       30     СПб
c       22  Казань

In [10]:
data = [
    ["Anna",25,"Moskow"],
    ["Ivan",30,"SPb"],
    ["Olga",22,"Kazan"]
]
df = pd.DataFrame(data, columns = ["Name","Age","City"])
print(df)

   Name  Age    City
0  Anna   25  Moskow
1  Ivan   30     SPb
2  Olga   22   Kazan

In [13]:
data = [
    {"Name": "Anna","Age":25,"City":"Moskow"},
    {"Name":"Ivan","Age":30},
    {"Name":"Olga","Age":22,"City":"Kazan"}
]
df = pd.DataFrame(data)
print(df)

   Name  Age    City
0  Anna   25  Moskow
1  Ivan   30     NaN
2  Olga   22   Kazan

In [3]:
import numpy as np
data = np.array([
    ["Anna",25,"Moskow"],
    ["Ivan",30,"SPb"],
    ["Olga",22,"Kazan"]
])
df = pd.DataFrame(data, columns=["Name","Age","City"])
print(df)

   Name Age    City
0  Anna  25  Moskow
1  Ivan  30     SPb
2  Olga  22   Kazan

In [17]:
numeric_data = np.array([
    [25,65.5],
    [30, 78.2],
    [22, 54.3]
])
df = pd.DataFrame(numeric_data,columns=["Age","Weight"])
print(df)

    Age  Weight
0  25.0    65.5
1  30.0    78.2
2  22.0    54.3

In [18]:
df = pd.DataFrame(columns=["Name","Age","City"])
print(df)

Empty DataFrame
Columns: [Name, Age, City]
Index: []

In [19]:
df.loc[0]=["Anna",25,"Moskow"]
df.loc[1]=["Ivan",30,"SPb"]
print(df)

   Name  Age    City
0  Anna   25  Moskow
1  Ivan   30     SPb

In [24]:
df = pd.read_csv("data.csv")
print(df.head())

    1   ; 72   00   ; 1  00   ; 80  00   ; 47   00   ; 6  00   ; 25  \
0   2   ; 48  00   ; 92  00   ; 82  00   ; 37  00   ; 13  00   ; 27
1   3   ; 78  00   ; 39   00   ; 9  00   ; 79  00   ; 59  00   ; 92
2   4   ; 63  00   ; 57  00   ; 57  00   ; 82   00   ; 3  00   ; 61
3   5   ; 61   00   ; 5  00   ; 57  00   ; 15  00   ; 98  00   ; 58
4   6   ; 72  00   ; 55  00   ; 54  00   ; 74  00   ; 63  00   ; 55

   00   ; 13   00   ; 69   00   ; 3  00   ; 89  00   ;;;;;;;;;;;;
0  00   ; 15  00   ; 100  00   ; 50  00   ; 19  00   ;;;;;;;;;;;;
1  00   ; 56   00   ; 23   00   ; 1  00   ; 92  00   ;;;;;;;;;;;;
2  00   ; 25   00   ; 74  00   ; 54  00   ; 72  00   ;;;;;;;;;;;;
3  00   ; 43   00   ; 76   00   ; 7  00   ; 79  00   ;;;;;;;;;;;;
4  00   ; 98   00   ; 20  00   ; 70  00   ; 96  00   ;;;;;;;;;;;;

In [25]:
df = pd.read_csv("data.csv", sep=";", index_col=0, na_values=["?","N/A"])
print(df.head())

        72,00       1,00      80,00      47,00       6,00      25,00     \
 1
2.0     48,00      92,00      82,00      37,00      13,00      27,00
3.0     78,00      39,00       9,00      79,00      59,00      92,00
4.0     63,00      57,00      57,00      82,00       3,00      61,00
5.0     61,00       5,00      57,00      15,00      98,00      58,00
6.0     72,00      55,00      54,00      74,00      63,00      55,00

        13,00       69,00       3,00      89,00     ...  Unnamed: 13  \
 1                                                  ...
2.0     15,00      100,00      50,00      19,00     ...          NaN
3.0     56,00       23,00       1,00      92,00     ...          NaN
4.0     25,00       74,00      54,00      72,00     ...          NaN
5.0     43,00       76,00       7,00      79,00     ...          NaN
6.0     98,00       20,00      70,00      96,00     ...          NaN

       Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  \
 1
2.0            NaN          NaN          NaN          NaN          NaN
3.0            NaN          NaN          NaN          NaN          NaN
4.0            NaN          NaN          NaN          NaN          NaN
5.0            NaN          NaN          NaN          NaN          NaN
6.0            NaN          NaN          NaN          NaN          NaN

       Unnamed: 19  Unnamed: 20  Unnamed: 21  Unnamed: 22
 1
2.0            NaN          NaN          NaN          NaN
3.0            NaN          NaN          NaN          NaN
4.0            NaN          NaN          NaN          NaN
5.0            NaN          NaN          NaN          NaN
6.0            NaN          NaN          NaN          NaN

[5 rows x 22 columns]

In [26]:
df.to_csv("output.csv", index=False)

In [33]:
import sqlite3
conn = sqlite3.connect("database.db")

conn.execute('''
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER,
        name TEXT,
        email TEXT
    )
''')
conn.execute("INSERT INTO users VALUES (1, 'Alice', 'alice@example.com')")
conn.execute("INSERT INTO users VALUES (2, 'Bob', 'bob@example.com')")
conn.commit()

In [34]:
df = pd.read_sql("SELECT * FROM users", conn)
print(df.head())

   id   name              email
0   1  Alice  alice@example.com
1   2    Bob    bob@example.com

In [35]:
df.to_sql("users", conn, if_exists="replace", index=False)

2

In [36]:
data = {
    "Имя": ["Анна", "Иван", "Ольга", "Петр", "Мария", "Сергей"],
    "Возраст": [25, 30, 22, 40, 35, 28],
    "Город": ["Москва", "СПб", "Казань", "Новосибирск", "Екатеринбург", "Сочи"]
}
df = pd.DataFrame(data)
print(df.head(3))

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [37]:
print(df.tail(2))

      Имя  Возраст         Город
4   Мария       35  Екатеринбург
5  Сергей       28          Сочи

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Имя      6 non-null      str
 1   Возраст  6 non-null      int64
 2   Город    6 non-null      str
dtypes: int64(1), str(2)
memory usage: 276.0 bytes

In [40]:
print(df.describe())

        Возраст
count   6.00000
mean   30.00000
std     6.60303
min    22.00000
25%    25.75000
50%    29.00000
75%    33.75000
max    40.00000

In [42]:
data = {
    "Имя": ["Анна", "Иван", "Ольга", "Петр"],
    "Возраст": [25, 30, 22, 40],
    "Город": ["Москва", "СПб", "Казань", "Новосибирск"]
}

df = pd.DataFrame(data, index=["a", "b", "c", "d"])
print(df)

     Имя  Возраст        Город
a   Анна       25       Москва
b   Иван       30          СПб
c  Ольга       22       Казань
d   Петр       40  Новосибирск

In [43]:
print(df.loc["c","Город"])

Казань

In [46]:
print(df.loc[["a","c"]])

     Имя  Возраст   Город
a   Анна       25  Москва
c  Ольга       22  Казань

In [47]:
print(df.loc[:,["Имя","Город"]])

     Имя        Город
a   Анна       Москва
b   Иван          СПб
c  Ольга       Казань
d   Петр  Новосибирск

In [48]:
print(df.loc[df["Возраст"]>25])

    Имя  Возраст        Город
b  Иван       30          СПб
d  Петр       40  Новосибирск

In [49]:
print(df.iloc[1])

Имя        Иван
Возраст      30
Город       СПб
Name: b, dtype: object

In [50]:
print(df.iloc[2,2])

Казань

In [51]:
print(df.iloc[[0,2]])

     Имя  Возраст   Город
a   Анна       25  Москва
c  Ольга       22  Казань

In [52]:
print(df.iloc[1:3])

     Имя  Возраст   Город
b   Иван       30     СПб
c  Ольга       22  Казань

In [53]:
print(df.iloc[:,[0,2]])

     Имя        Город
a   Анна       Москва
b   Иван          СПб
c  Ольга       Казань
d   Петр  Новосибирск

In [54]:
print(df.at["c","Город"])

Казань

In [55]:
print(df.iat[2,2])

Казань

In [15]:
data = {
    "Имя": ["Анна", "Иван", "Ольга"],
    "Возраст": [25, 30, 22]
}

df = pd.DataFrame(data)
df["Город"] = ["Москва", "СПб", "Казань"]  
print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [17]:
df["Страна"]="Россия"
print(df)

     Имя  Возраст   Город  Страна
0   Анна       25  Москва  Россия
1   Иван       30     СПб  Россия
2  Ольга       22  Казань  Россия

In [11]:
df["Возраст в месяцах"]=df["Возраст"]*12
print(df)

     Имя  Возраст   Город  Страна  Возраст в месяцах
0   Анна       25  Москва  Россия                300
1   Иван       30     СПб  Россия                360
2  Ольга       22  Казань  Россия                264

In [12]:
df = df.assign(Зарплата=[50000,60000,45000])
print(df)

     Имя  Возраст   Город  Страна  Возраст в месяцах  Зарплата
0   Анна       25  Москва  Россия                300     50000
1   Иван       30     СПб  Россия                360     60000
2  Ольга       22  Казань  Россия                264     45000

In [13]:
df["Категория возраста"]=df["Возраст"].apply(lambda x: "Молодой" if x<30 else "Взрослый")
print(df)

     Имя  Возраст   Город  Страна  Возраст в месяцах  Зарплата  \
0   Анна       25  Москва  Россия                300     50000
1   Иван       30     СПб  Россия                360     60000
2  Ольга       22  Казань  Россия                264     45000

  Категория возраста
0            Молодой
1           Взрослый
2            Молодой

In [18]:
df.loc[3]=["Петр",40,"Новосибриск","Россия"]
print(df)

     Имя  Возраст        Город  Страна
0   Анна       25       Москва  Россия
1   Иван       30          СПб  Россия
2  Ольга       22       Казань  Россия
3   Петр       40  Новосибриск  Россия

In [22]:
new_data = pd.DataFrame([{"Имя":"Сергей", "Возраст":30 ,"Город":"Сочи", "Страна":"Россия"}])
df = pd.concat([df, new_data], ignore_index=True)
print(df)

      Имя  Возраст        Город  Страна
0    Анна       25       Москва  Россия
1    Иван       30          СПб  Россия
2   Ольга       22       Казань  Россия
3    Петр       40  Новосибриск  Россия
4  Сергей       30         Сочи  Россия

In [23]:
new_rows = pd.DataFrame([
    {"Имя": "Дмитрий", "Возраст": 31, "Город": "Самара", "Страна": "Россия"},
    {"Имя": "Елена", "Возраст": 27, "Город": "Воронеж", "Страна": "Россия"}
])

df = pd.concat([df, new_rows], ignore_index=True)
print(df)

       Имя  Возраст        Город  Страна
0     Анна       25       Москва  Россия
1     Иван       30          СПб  Россия
2    Ольга       22       Казань  Россия
3     Петр       40  Новосибриск  Россия
4   Сергей       30         Сочи  Россия
5  Дмитрий       31       Самара  Россия
6    Елена       27      Воронеж  Россия

In [24]:
df.loc["новый"]=["Артем",33,"Калуга","Россия"]
print(df)

           Имя  Возраст        Город  Страна
0         Анна       25       Москва  Россия
1         Иван       30          СПб  Россия
2        Ольга       22       Казань  Россия
3         Петр       40  Новосибриск  Россия
4       Сергей       30         Сочи  Россия
5      Дмитрий       31       Самара  Россия
6        Елена       27      Воронеж  Россия
новый    Артем       33       Калуга  Россия

In [27]:
data = {
    "Имя": ["Анна", "Иван", "Ольга"],
    "Возраст": [25, 30, 22],
    "Город": ["Москва", "СПб", "Казань"],
    "Зарплата": [50000, 60000, 45000]
}
df = pd.DataFrame(data)
df = df.drop(columns=["Зарплата"])
print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [26]:
df = df.drop(columns=["Возраст","Город"])
print(df)

     Имя
0   Анна
1   Иван
2  Ольга

In [28]:
del df["Имя"]
print(df)

   Возраст   Город
0       25  Москва
1       30     СПб
2       22  Казань

In [29]:
df["Имя"] = ["Анна", "Иван", "Ольга"]
удаленный_столбец = df.pop("Имя")
print(удаленный_столбец)

0     Анна
1     Иван
2    Ольга
Name: Имя, dtype: str

In [30]:
df = pd.DataFrame(data)
df = df.drop(index=1)
print(df)

     Имя  Возраст   Город  Зарплата
0   Анна       25  Москва     50000
2  Ольга       22  Казань     45000

In [31]:
df = pd.DataFrame(data)
df = df.drop(index=[0,2])
print(df)

    Имя  Возраст Город  Зарплата
1  Иван       30   СПб     60000

In [34]:
df = pd.DataFrame(data)
df = df[df["Возраст"]>25]
print(df)

    Имя  Возраст Город  Зарплата
1  Иван       30   СПб     60000

In [35]:
df = df.reset_index(drop=True)
print(df)

    Имя  Возраст Город  Зарплата
0  Иван       30   СПб     60000

In [36]:
df = pd.DataFrame(data)
df.loc[3]=["Мария", None, "Самара",55000]
df = df.dropna()
print(df)

     Имя Возраст   Город  Зарплата
0   Анна      25  Москва     50000
1   Иван      30     СПб     60000
2  Ольга      22  Казань     45000

In [37]:
df = pd.DataFrame({
    "Имя": ["Анна", "Иван", "Анна", "Ольга"],
    "Возраст": [25, 30, 25, 22]
})

df = df.drop_duplicates()
print(df)

     Имя  Возраст
0   Анна       25
1   Иван       30
3  Ольга       22

In [49]:
data = {
    "Имя": ["Анна", "Иван", "Ольга", "Петр", "Мария"],
    "Возраст": [25, 30, 22, 40, 35],
    "Город": ["Москва", "СПб", "Казань", "Новосибирск", "СПб"],
    "Зарплата": [50000, 60000, 45000, 70000, 65000]
}

df = pd.DataFrame(data)
print(df)

     Имя  Возраст        Город  Зарплата
0   Анна       25       Москва     50000
1   Иван       30          СПб     60000
2  Ольга       22       Казань     45000
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000

In [44]:
df_filt = df.query("Возраст >30")
print(df_filt)

     Имя  Возраст        Город  Зарплата
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000

In [47]:
df_filt = df.query("Город == 'СПб' and Зарплата > 60000")
print(df_filt)

     Имя  Возраст Город  Зарплата
4  Мария       35   СПб     65000

In [48]:
min_age = 25
df_filt = df.query("Возраст > @min_age")
print(df_filt)

     Имя  Возраст        Город  Зарплата
1   Иван       30          СПб     60000
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000

In [60]:
data = {
    "Имя": ["Анна", "Иван", "Ольга", "Петр", "Мария"],
    "Возраст": [25, 30, 22, 40, 35],
    "Город": ["Москва", "СПб", "Казань", "Новосибирск", "СПб"],
    "Зарплата": [50000, 60000, 45000, 70000, 65000]
}

df = pd.DataFrame(data)
print(df)

     Имя  Возраст        Город  Зарплата
0   Анна       25       Москва     50000
1   Иван       30          СПб     60000
2  Ольга       22       Казань     45000
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000

In [58]:
df_filt = df[df["Город"].isin(["Москва", "СПб"])]
print(df_filt)

     Имя  Возраст   Город  Зарплата
0   Анна       25  Москва     50000
1   Иван       30     СПб     60000
4  Мария       35     СПб     65000

In [61]:
df_filt = df[~df["Город"].isin(["Москва", "СПб"])]
print(df_filt)

     Имя  Возраст        Город  Зарплата
2  Ольга       22       Казань     45000
3   Петр       40  Новосибирск     70000

In [63]:
df_filt = df[df["Возраст"].between(25, 35)]
print(df_filt)

     Имя  Возраст   Город  Зарплата
0   Анна       25  Москва     50000
1   Иван       30     СПб     60000
4  Мария       35     СПб     65000

In [64]:
df_filt = df[df["Возраст"].between(25, 35, inclusive="neither")]
print(df_filt)

    Имя  Возраст Город  Зарплата
1  Иван       30   СПб     60000

In [67]:
data = {
    "Имя": ["Анна", "Иван", "Ольга", "Петр", None],
    "Возраст": [25, 30, 22, None, 35],
    "Город": ["Москва", "СПб", "Казань", "Новосибирск", "СПб"],
}

df = pd.DataFrame(data)
print(df)

     Имя  Возраст        Город
0   Анна     25.0       Москва
1   Иван     30.0          СПб
2  Ольга     22.0       Казань
3   Петр      NaN  Новосибирск
4    NaN     35.0          СПб

In [68]:
print(df.count())

Имя        4
Возраст    4
Город      5
dtype: int64

In [70]:
print(df["Город"].value_counts())

Город
СПб            2
Москва         1
Казань         1
Новосибирск    1
Name: count, dtype: int64

In [71]:
print(df["Город"].value_counts(sort=False))

Город
Москва         1
СПб            2
Казань         1
Новосибирск    1
Name: count, dtype: int64

In [72]:
print(df["Имя"].value_counts(dropna=False))

Имя
Анна     1
Иван     1
Ольга    1
Петр     1
NaN      1
Name: count, dtype: int64

In [73]:
print(df.nunique())

Имя        4
Возраст    4
Город      4
dtype: int64

In [74]:
print(df["Имя"].nunique(dropna=False))

5

In [75]:
print(df.isna().sum())

Имя        1
Возраст    1
Город      0
dtype: int64

In [76]:
data = {
    "Имя": ["Анна", "Иван", "Ольга", "Петр", "Мария"],
    "Возраст": [25, 30, 22, 40, 35],
    "Город": ["Москва", "СПб", "Казань", "Новосибирск", "СПб"],
    "Зарплата": [50000, 60000, 45000, 70000, 65000]
}

df = pd.DataFrame(data)
print(df)

     Имя  Возраст        Город  Зарплата
0   Анна       25       Москва     50000
1   Иван       30          СПб     60000
2  Ольга       22       Казань     45000
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000

In [77]:
df_sort = df.sort_values(by="Возраст")
print(df_sort)

     Имя  Возраст        Город  Зарплата
2  Ольга       22       Казань     45000
0   Анна       25       Москва     50000
1   Иван       30          СПб     60000
4  Мария       35          СПб     65000
3   Петр       40  Новосибирск     70000

In [79]:
df_sort = df.sort_values(by="Возраст", ascending=False)
print(df_sort)

     Имя  Возраст        Город  Зарплата
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000
1   Иван       30          СПб     60000
0   Анна       25       Москва     50000
2  Ольга       22       Казань     45000

In [81]:
df_sort = df.sort_values(by=["Возраст","Зарплата"], ascending=[True, 
                                                               False])
print(df_sort)

     Имя  Возраст        Город  Зарплата
2  Ольга       22       Казань     45000
0   Анна       25       Москва     50000
1   Иван       30          СПб     60000
4  Мария       35          СПб     65000
3   Петр       40  Новосибирск     70000

In [85]:
df.loc[5] = ["Елена", None, "Самара", 55000] 
df_sort = df.sort_values(by="Возраст", na_position="first")
print(df_sort)

     Имя Возраст        Город  Зарплата
5  Елена    None       Самара     55000
2  Ольга      22       Казань     45000
0   Анна      25       Москва     50000
1   Иван      30          СПб     60000
4  Мария      35          СПб     65000
3   Петр      40  Новосибирск     70000

In [86]:
df_sort = df.sort_index()
print(df_sort)

     Имя Возраст        Город  Зарплата
0   Анна      25       Москва     50000
1   Иван      30          СПб     60000
2  Ольга      22       Казань     45000
3   Петр      40  Новосибирск     70000
4  Мария      35          СПб     65000
5  Елена    None       Самара     55000

In [87]:
df_sort = df.sort_index(ascending=False)
print(df_sort)

     Имя Возраст        Город  Зарплата
5  Елена    None       Самара     55000
4  Мария      35          СПб     65000
3   Петр      40  Новосибирск     70000
2  Ольга      22       Казань     45000
1   Иван      30          СПб     60000
0   Анна      25       Москва     50000

In [88]:
df = pd.DataFrame({
    "Имя": ["Анна", "Иван", "Ольга"],
    "Возраст": [25, 30, 22],
    "Город": ["Москва", "СПб", "Казань"]
})

print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [89]:
from IPython.display import display
display(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [94]:
data = {
    "Имя": ["Анна", "Иван", "Ольга", "Петр", "Мария","Мария"],
    "Возраст": [25, 30, 22, 40, 35, 43],
    "Город": ["Москва", "СПб", "Казань", "Новосибирск", "СПб","Новосибирск",],
    "Зарплата": [50000, 60000, 45000, 70000, 65000,90000]
}

df = pd.DataFrame(data)
df.head(3)

     Имя  Возраст   Город  Зарплата
0   Анна       25  Москва     50000
1   Иван       30     СПб     60000
2  Ольга       22  Казань     45000

In [93]:
df.tail(3)

     Имя  Возраст        Город  Зарплата
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000
5  Мария       43  Новосибирск     90000

In [95]:
pd.set_option("display.max_rows", 100)

In [96]:
pd.set_option("display.max_columns", 50)

In [97]:
pd.set_option("display.max_colwidth", None)

In [98]:
pd.set_option("display.float_format", "{:.2f}".format)#отображение чисел с плавающе точкой

In [100]:
df = pd.DataFrame({
    "Имя": ["Анна", "Иван", "Ольга"],
    "Возраст": [25, 30, 22],
    "Город": ["Москва", "СПб", "Казань"]
})
df.style.set_properties(**{"background-color": "lightgray", "color": "black"})

html_table = df.to_html()
with open("table.html", "w", encoding="utf-8") as f:
    f.write(html_table)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [104]:
styled_df = df.style.set_properties(**{"background-color": "lightgray", "color": "blue"})
display(styled_df)